### ISSUE TITLE
BUG: In cases where the entire message is a punctuation or other short string, the lexicon counter returns len(lexicon) or other large number

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#105]
It seems that in cases where the message is entirely made up of punctuation (e.g., the message is ':)' and therefore the post-processed message is empty), the lexicon counter ends up returning the size of the entire lexicon rather than the expected value (0).

Example of CSV where this issue is evident: https://github.com/Watts-Lab/team-process-map/blob/c0a16996d73bf3964e50d50d64b3b7d4403518af/feature_engine/output/csopII_output_chat_level.csv

**Comment by xehu** [comment]
In a small test at the bottom of here: https://github.com/Watts-Lab/team-process-map/blob/lexicon-testing/feature_engine/features/preprocess_lexicons.ipynb

I am testing some of these edge cases. Specifically, I have noticed:
- 'hi!' generates really large values (e.g., 17) under certain headings, like 'bio' and 'cognitive mech'
- first_person ALWAYS returns zero, even when I clearly use first-person pronouns
- when there are only symbols and no words, it generates huge values (e.g., 7686 for 'bio')

**Comment by yashveersinghsohi** [comment]
I have linked a [PR](https://github.com/Watts-Lab/team-process-map/pull/111) that I have been using to deal with this bug. If anyone finds any other bugs in the meantime, lets update them here and add fixes for them in the same PR?
