### ISSUE TITLE
Validating and Fine-Tuning BERT Features for Context Specificity

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#134]
A known issue is that, while BERT works fairly well out-of-the-box, it doesn't always pick up on a few context-specific details, for example:

- "asshole" in the Juries dataset: the juries dataset is from discussion on r/AmITheAsshole, and therefore it is not a "negative" speech act to call someone an asshole. However, BERT doesn't know this, and we end up with (false) negatives.
- context-specific vocabulary: e.g., people in the task may have screen names ("littleMonkey," "smallCow") and other words that are not recognized by a standard model.

Thus, this issue proposes checking for / addressing the following:

- [ ] Can we evaluate how "well" BERT is doing in terms of the positivity/neutrality/negativity? If you need hand-labels, I'm happy to help create a HIT for MTurk and get some human validation labels.
- [ ] Can we improve upon the known shortcomings (described above)?

Some ideas for improving on these shortcomings include:
- (Naive) preprocessing the juries data to remove instances of "asshole," replacing it with the empty string or some neutral equivalent term, e.g., "individual at fault"
- (Advanced) Fine-Tuning the BERT model on the entire Juries dataset before getting the BERT vectors?

**Comment by agshruti12** [comment]
Censored the data to replace "asshole" with "individual at fault" and reran all BERT metrics + visualization. Positivity exhibited no change, whereas neutrality went up a smidge, and negativity went down the same amount. Validates our current method of calculating BERT sentiment.
