### ISSUE TITLE
Create a Dictionary to Track Feature Dependencies

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#209]
According to our Communication Feature Database (https://glitter-runner-dfb.notion.site/e0fd0ceb6c6c47d9b8e3bec95d8af78f?v=3050cfbe883e4d9ea1954bc67bf12a46), we currently generate 122 unique features across all of our different functions --- that's a lot!

However, these features were the contributions of many RA's over time, and while most of the features are modular, different features may have different dependencies. For example, some of the features depend on the "lexical" (i.e., wordcount-related) features being generated first; they then look for the outputs of specific columns.

Example: Proportion of 1st person pronouns
Code: https://github.com/Watts-Lab/team-process-map/blob/main/feature_engine/features/other_lexical_features.py
```
def get_proportion_first_pronouns(df):
  return(df.apply(lambda row: row["first_person_raw"] / row["num_words"] if row["num_words"] > 0 else 0, axis=1))
```

We should create a dictionary (possibly within the top-level `feature_engine/` folder) that tracks the following:
1. The names of all our features;
2. The names of the file(s) containing the features;
3. The names of the columns(s) generated by the features;
4. Whether the feature is at the chat- or conversation-level;
5. Relevant semantic groupings for the feature (e.g., "emotion features");
6. Key dependencies of the features (**NOTE**: _this is where there will need to be some design decisions_; how do we want to handle storing dependencies? Will this be just a string description, or a more structured way of expressing this information? There are also different forms of dependency --- in some cases, certain features depend on things like having vector data (see discursive diversity, forward flow, mimicry); others have package dependencies (e.g., ConvoKit Politeness is dependent on Spacy); still others depend on other features (such as the lexical example). We may therefore have to create different columns to log different types of dependencies.);
7. A link to the wiki page of the feature.

Most of this information is already in the [Communication Feature Database](https://glitter-runner-dfb.notion.site/e0fd0ceb6c6c47d9b8e3bec95d8af78f?v=3050cfbe883e4d9ea1954bc67bf12a46), but we need some way to have a structured log of all the features in the repository, and then referencing it when we give users the option to choose features (https://github.com/Watts-Lab/team-process-map/issues/202; https://github.com/Watts-Lab/team-process-map/issues/203).

**Comment by xehu** [comment]
Hi @zhouhelena, amazing job on your first pass on this task! I just took a look at the branch (https://github.com/Watts-Lab/team-process-map/tree/helena/package_task3), and I've made some changes. This comment will describe some of the edits, as well as next steps for this task.

# Consolidate Feature Information into a Single Dictionary
The main change I made to the branch was to consolidate the hard-coded dictionaries in `feature_builder.py` (screenshot below) with `feature_dictionary.json`.
![Screenshot 2024-06-14 at 12 24 29 PM](https://github.com/Watts-Lab/team-process-map/assets/28793641/aeaf38a4-dc0f-4490-bfca-88996e1bb896)

The code I wrote lives here (generate_feature_dict.py): https://github.com/Watts-Lab/team-process-map/blob/c9a4ca16a2b4d11251b4f3d67b27d2eed8cf1bef/feature_engine/generate_feature_dict.py

The idea is to create a "one-stop-shop" where all of the information we could care about regarding a given feature lives in a single location. This way, we don't have to remember to update both the main JSON and the dictionaries inside `feature_builder.py`; when someone adds a new feature, they just add it to a single location, and it will propagate throughout.

Here is how the dictionary later gets read in (in `feature_builder.py`):
```
# Read in the feature dictionary
        with open('features.pkl', 'rb') as file:
            feature_dictionary = pickle.load(file)

        # set which chat / conversation feature methods we want to calculate
        self.feature_methods_chat = {key: feature_dictionary[key]["function"] for key in self.features_to_calculate if  feature_dictionary[key]["level"] == "Chat"}
        self.feature_methods_conv = {key: feature_dictionary[key]["function"] for key in self.features_to_calculate if  feature_dictionary[key]["level"] == "Conversation"}
```

## Next Steps
With this change, I think we could likely do the following:
- [ ] Delete feature_dictionary.json and features.json, as they are now consolidated;
- [ ] Modify generate_feature_dict.py to combine `feature_methods_chat` and `feature_methods_conv`, as we can separately build these in `feature_builder.py`;
- [ ] Ensure that the names in the feature dictionary match the names in methods dictionary --- in my initial pass, the names in the dictionary didn’t always perfectly match, and I made a few manual edits. In addition, the methods generating the aggregates ("Conversation Level Aggregates", "User Level Aggregates") are missing entries in the dictionary, and they need to be added back.

# Expand the Default Set and Update How the Feature List is Created.
In my edits, I made the default set longer ---  I’d rather err on the side of defaulting to generating a feature (assuming it's not too time costly or requires a certain data format such that it would throw an error), because defaults are really powerful. If we don't put something in the default, chances are that only a very small number of users will actually make a change to the parameters and find the feature. Thus, the smaller our defaults, the less useful our package will be! I think we should take another pass on the default list with this philosophy in mind; i.e., we should have a proactive reason *not* to default, as opposed to having a proactive reason to include a feature.

I also had to make a few changes with the way that the feature list is ordered --- it turns out that there are certain dependencies that require some features to be calculated before others (this is explained in a comment inline). For example, "Word Count" needs to be called before "Information Exchange," as the latter uses the former to compute the feature. But more generally, the way that the methods are designed seem to hide some interdependencies that need to be cleaned up in next steps.

## Next Steps
- [ ] Look at some of these dependencies, and figure out error catching --- what happens if the user doesn't want to calculate the word count feature, but they DO want to calculate information exchange? How will we catch the error? Will we just silently calculate it anyway?
- [ ] Some of the functions are "double whammy"s, in that the method in ChatLeveFeaturesCalculator is the same for multiple features --- for example, Conversational Repair, Word Type-Token Ratio, Proportion of First Person Pronouns, and Questions all use the same method, so we would end up doing redundant work if we call that method 4 times. More importantly, it's confusing that the same method generates 4 completely different features, so I think we should split it up.
- [ ] Add a list for **features people DON'T want**; right now, there is a list of features that people do want (the additional_feature parameter), but I think that we also want the reverse: give people the option to not generate things that exist in the defaults.
- [ ] (Just food for thought) I think there is a natural separation between the lexical features / things that don’t require generating vectors, and features that require generating vectors (as those are slower); I wonder if there's a version of the defaults where you JUST get the lexical features, versus a default where you get all the features we think are potentially useful --- perhaps a flag where you can turn off all features that require BERT / Sentence vectors?
- [ ] (Minor change) Consider renaming the additional_features parameter something more positive, like `custom_features`? I feel like `additional` makes the features seem unimportant for whatever reason.

# General next step: Connecting the Feature Dictionary to the Testing Suite
Currently, we are using the output CSV's to calculate how many features we have to test:
```
test_chat_df =  pd.read_csv("../output/chat/test_chat_level_chat.csv")
test_conv_df =  pd.read_csv("../output/conv/test_conv_level_conv.csv")
num_features_chat = test_chat_df.columns.size - 7
num_tested_chat = test_chat_df['expected_column'].nunique()
num_features_conv = test_conv_df.columns.size - 7
num_tested_conv = test_conv_df['expected_column'].nunique()
```

I think that Helena and @agshruti12 can work together to use the "master dictionary" to do this more intelligently --- if we trust that the dictionary to have the right number of features, we can just go through the dictionary (and the columns stored) to track how much test coverage we have!

**Comment by sundy1994** [comment]
Hi @xehu! I went through the feature dictionary, and I have some questions:

1. Is it correct to say we only have chat level and conversation level features? In the feature database, 'message quantity' is labeled as conversation and speaker level. We do have 'calculate_user_level_features.py' but they are in neither the database nor the dictionary. Besides, the NER feature is missing too. Right now, I'm confused about what are all the features and where they belong.
2. Many features are sharing the same function. For example, in chat level features, both "TextBlob Polarity" and "TextBlob Subjectivity" are included in `calculate_textblob_sentiment()`. This is troublesome for managing dependencies. In my opinion, we should either update our Wiki/database, or split Python functions that are shared, so that each feature only has one corresponding function.
3. In terms of managing the dependencies/prerequisites, I propose we add a field in the feature dictionary: `'dependencies': [dep_1, dep_2, ...]`. In feature builder, we first go through user's requirements to get a list of features they want: `feature_list = default_features + custom_features - exclude_features`. Then we go through them and add back missing features that are prerequisites: 
```
add = []
for feature in feature_list:
     prereq = feature_dict[feature]["dependencies"]
     for req in prereq:
          if req not in feature_list:
               add.append(req)
feature_list += add
```
The only problem is that will the dependencies also have their own dependencies. If that's possible I guess a while loop is necessary. Another solution is to include as many default features as possible. In this way, we won't need to add the most basic features manually.
