### ISSUE TITLE
Dependency Issue: "ImportError: cannot import name 'triu' from 'scipy.linalg'" 

### ISSUE THREAD

**Issue by rowbotham-evan** [Watts-Lab/team-process-map#239]
# Depreciation Issue
- When running featurizer you may run into the following error: 
  ` ImportError: cannot import name 'triu' from 'scipy.linalg' ` 

- The scipy.linalg functions tri, triu (the one we are using) & tril are deprecated and will be removed in SciPy 1.13. If you are working on a newer version of python, and just used:
  ` pip install scipy `
it will most likely install a newer version that have already depreciated scipy.linalg  
 - **Solution**: install an older version of scipy, run (for more details see [here](https://stackoverflow.com/questions/78279136/importerror-cannot-import-name-triu-from-scipy-linalg-when-importing-gens)): 
 ` pip install scipy==1.12 `

**Comment by xehu** [comment]
Our requirements.txt file already specifies 1.12.0:

> scipy==1.12.0

So I think if you are installing using the requirements file, everything is good for now! In the future, we can reopen/resolve if we need to upgrade to 1.13.
