### ISSUE TITLE
Look into Original Data/Code from Previous Papers

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#50]
Try to find the original datasets and/or code for C12 and C9 (Assertiveness).

Can we replicate these models? Can we use that data for pretraining?

**Comment by Candicecao8** [comment]
- C12: Found it!! I put the link in our master sheet :)
- C9: [This paper](https://web.stanford.edu/class/cs224s/project/reports_2017/Aaron_Zweig.pdf) indicated that this dataset is called _the Stanford Linguistic Departments SpeedDate Corpus_. I googled it but didn't find any resources available. Maybe Emily could use some of your Stanford connections? :)
