### ISSUE TITLE
❓Questions about Task Implementation

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#61]
I posted these questions in #ht-task-implementation, but I'd love to surface them here as well!

- **Grading the Group Typing Task:** For a project that I'm running with Katy Milkman, I’m working on setting up an experiment using a game similar to the Group Typing task, except it is single-player (in which you have to type as many words as possible, earning +1 per word, -1 per typo or missed word). I know we already implemented a version in Empirica, so I’m wondering: could I take a look at the code for how we grade the tasks / calculate the score? How do you detect a typo (do you tokenize the entire submission and then compare word by word)? I would really appreciate a quick chat or reference with the person who implemented Group Typing, so that I don't have to repeat this work!
- **Plugging Team Process Map into Our Integrative Experiments:** For #team-process-map, I would love to --- in the long run --- analyze the chat data from any integrative experiments we run! As I've mentioned in https://github.com/Watts-Lab/team-process-map/issues/5, I'm hoping for the communication data analysis framework to be generalizable enough to analyze anything that has {team chats, outcome data}, and I envision designing the models to seamlessly plug into the task map. (That is, I would build the analysis on top of the task map and ask: for which regions of tasks are certain types of communication prevalent?) Thus, I would love to know how much chat data we currently capture, and in what format? I just want to establish contact early enough so that the system is set up so that I can easily use the chat form of the data later, and also to engage the relevant stakeholders to make this possible.

**Comment by shapeseas** [comment]
@xehu the implementation of any collaborative typing now uses Etherpad, which is an open source collaborative editor: https://etherpad.org/. We don't deal with typos in any of our tasks as far as I know, but I imagine Etherpad has functionality built in to do that.

Code is hosted here: https://github.com/Watts-Lab/etherpad-wattslab .

**Comment by JamesPHoughton** [comment]
We use this as a GH action to spellcheck deliberation topics: https://facelessuser.github.io/pyspelling/

**Comment by xehu** [comment]
Comments from lab meeting:
- Look into a diff or diffchecker library: https://www.diffchecker.com/text-compare/
- Chats are collected, but people are relatively laconic (they don't chat as much)
